name: 'Build, Test, Deploy'

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
      - beta

env:
  NODE_VERSION_UI: '18'
  NODE_VERSION_CDK: '18'
  GO_VERSION_API: '^1.20.4'
  GO_VERSION_OTEL_COLLECTOR: '^1.20.4'
  WORKSPACE_ARTIFACT_UI: 'gw2auth_ui_artifact'
  WORKSPACE_ARTIFACT_API: 'gw2auth_api_artifact'
  WORKSPACE_ARTIFACT_OTEL_COLLECTOR: 'otel_collector_artifact'
  WORKSPACE_ARTIFACT_CDK: 'gw2auth_cdk_artifact'

jobs:
  build_ui:
    name: 'Build UI'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CDK_SSH_KEY }}
          submodules: true
      - name: 'Setup node ${{ env.NODE_VERSION_UI }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION_UI }}
      - name: 'Install npm dependencies'
        working-directory: 'gw2auth.com-ui'
        run: 'npm install'
      - name: 'Build UI'
        working-directory: 'gw2auth.com-ui'
        run: 'npm run build'
      - name: 'Prepare UI resources bundle'
        working-directory: 'gw2auth.com-ui/dist'
        run: 'zip -r ../${{ env.WORKSPACE_ARTIFACT_UI }}.zip .'
      - name: 'Store UI artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT_UI }}
          path: 'gw2auth.com-ui/${{ env.WORKSPACE_ARTIFACT_UI }}.zip'
          retention-days: 1

  build_api:
    name: 'Build API'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CDK_SSH_KEY }}
          submodules: true
      - name: 'Setup go ${{ env.GO_VERSION_API }}'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION_API }}
      - name: 'Build API'
        working-directory: 'gw2auth.com-api'
        env:
          GOOS: 'linux'
          GOARCH: 'amd64' # keep this in sync with the arch configured in CDK!
          CGO_ENABLED: '0'
        run: 'go build -o bootstrap -tags "lambda,lambda.norpc,lambdahttpadapter.partial,lambdahttpadapter.echo,lambdahttpadapter.functionurl"'
      - name: 'Prepare lambda bundle'
        working-directory: 'gw2auth.com-api'
        run: '(chmod +x bootstrap && zip -q ${{ env.WORKSPACE_ARTIFACT_API }}.zip bootstrap && rm bootstrap)'
      - name: 'Store API artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT_API }}
          path: 'gw2auth.com-api/${{ env.WORKSPACE_ARTIFACT_API }}.zip'
          retention-days: 1

  build_otel_collector:
    name: 'Build otel collector'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CDK_SSH_KEY }}
          submodules: true
      - name: 'Setup go ${{ env.GO_VERSION_OTEL_COLLECTOR }}'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION_OTEL_COLLECTOR }}
      - name: 'Build otel collector'
        working-directory: 'opentelemetry-lambda/collector'
        env:
          GOOS: 'linux'
          GOARCH: 'amd64' # keep this in sync with the arch configured in CDK!
          CGO_ENABLED: '0'
        run: 'go build -o otel_collector'
      - name: 'Prepare lambda extension bundle'
        working-directory: 'opentelemetry-lambda/collector'
        run: |
          mkdir lambda_layer_bundle
          mkdir lambda_layer_bundle/extensions
          cp otel_collector lambda_layer_bundle/extensions/layer
          cp ../../collector.yaml lambda_layer_bundle/
          chmod +x lambda_layer_bundle/extensions/layer
          (cd lambda_layer_bundle && zip -r ../${{ env.WORKSPACE_ARTIFACT_OTEL_COLLECTOR }}.zip .)
      - name: 'Store otel collector artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT_OTEL_COLLECTOR }}
          path: 'opentelemetry-lambda/collector/${{ env.WORKSPACE_ARTIFACT_OTEL_COLLECTOR }}.zip'
          retention-days: 1

  build_and_synth_cdk:
    name: 'Build and synth cdk'
    runs-on: ubuntu-latest
    needs:
      - build_ui
      - build_api
      - build_otel_collector
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CDK_SSH_KEY }}
          submodules: true
      - name: 'Download artifacts'
        uses: actions/download-artifact@v3
        with:
          path: './gw2auth.com-cdk/resources'
      - name: 'Setup node ${{ env.NODE_VERSION_CDK }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION_CDK }}
      - name: 'Install cdk'
        run: 'npm install -g aws-cdk'
      - name: 'Install npm dependencies'
        working-directory: 'gw2auth.com-cdk'
        run: 'npm install'
      - name: 'Build cdk app'
        working-directory: 'gw2auth.com-cdk'
        run: 'npm run build'
      - name: 'Synth cdk'
        working-directory: 'gw2auth.com-cdk'
        run: 'cdk synth --app bin/cdk.js'
      - name: 'Store cdk synth artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT_CDK }}
          path: |
            gw2auth.com-cdk/cdk.out/
            gw2auth.com-cdk/cdk.json
          retention-days: 1

  deploy:
    name: 'Deploy'
    if: github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref == 'refs/heads/beta' && 'beta') || (github.ref == 'refs/heads/main' && 'prod') || 'unknown' }}
      url: ${{ (github.ref == 'refs/heads/beta' && 'https://beta.gw2auth.com') || (github.ref == 'refs/heads/main' && 'https://gw2auth.com') || 'unknown' }}
    needs:
      - build_and_synth_cdk
    steps:
      - name: 'Download cdk synth artifact'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.WORKSPACE_ARTIFACT_CDK }}
          path: .
      - name: 'Setup node ${{ env.NODE_VERSION_CDK }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION_CDK }}
      - name: 'Install cdk'
        run: 'npm install -g aws-cdk'
      - name: 'AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_CDK_ROLE }}
          aws-region: ${{ secrets.AWS_CDK_REGION }}
      - name: 'Deploy beta'
        if: github.ref == 'refs/heads/beta'
        run: 'cdk --app ./cdk.out deploy --require-approval never "*-Beta"'
      - name: 'Deploy prod'
        if: github.ref == 'refs/heads/main'
        run: 'cdk --app ./cdk.out deploy --require-approval never "*-Prod"'

  create_pull_request:
    name: 'Create PR'
    if: github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    needs:
      - deploy
    permissions:
      pull-requests: write
    steps:
      - name: 'Create PR'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: context.ref,
              base: 'main',
              state: 'open',
            });

            if (pulls.data.length < 1) {
              await github.rest.pulls.create({
                title: '[CI] Merge beta into main',
                owner: owner,
                repo: repo,
                head: context.ref,
                base: 'main',
                body: [
                  'This PR is auto-generated by',
                  '[actions/github-script](https://github.com/actions/github-script)',
                ].join('\n'),
              });
            } else {
              const existingPR = pulls.data[0];
              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: existingPR.number,
                body: [
                  `Updated by Job ${context.job}`,
                ].join('\n'),
              });
            }
