name: 'Trigger monorepo workflow'

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  trigger_monorepo_workflow:
    name: 'Trigger monorepo workflow'
    runs-on: ubuntu-latest
    steps:
      - name: 'Trigger monorepo workflow'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.token }}
          script: |
            const { owner, repo } = context.repo;
            const branch = context.ref.replace('refs/heads/', '');
            
            await github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: 'gw2auth.com-monorepo',
              workflow_id: 'create_pr_for_submodule.yml',
              ref: 'beta',
              inputs: {
                submodule: repo,
                submodule_ref: context.sha,
                submodule_branch: branch,
              },
            });